/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;
import modeloConection.ConexaoBD;
import modeloDAO.DAOUsuario;

/**
 *
 * @author Fabio
 */
public class TelaUsuario extends javax.swing.JFrame {
    
    BeansUsuario mod = new BeansUsuario();
    DAOUsuario dao = new DAOUsuario();
    ConexaoBD conex = new ConexaoBD();
    
    int flag = 0;
    
    public TelaUsuario() {
        initComponents();
        preencherTabela("select *from usuarios order by nome_usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jTextFieldLoginUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldSenhaUsuario = new javax.swing.JPasswordField();
        jPasswordFieldConfSenhaUsuario = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxTipoUsuario = new javax.swing.JComboBox();
        jButtonCadUsNovo = new javax.swing.JButton();
        jButtonCadUsSalvar = new javax.swing.JButton();
        jButtonCadUsAlterar = new javax.swing.JButton();
        jButtonCadUsExcluir = new javax.swing.JButton();
        jButtonCadUsCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCadUsPesquisar = new javax.swing.JTextField();
        jButtonCadUsBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadUsPesquisa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCadUsCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome");

        jTextFieldNomeUsuario.setEnabled(false);
        jTextFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeUsuarioActionPerformed(evt);
            }
        });

        jTextFieldLoginUsuario.setEnabled(false);
        jTextFieldLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Login");

        jLabel4.setText("Senha");

        jLabel5.setText("Confirmar Senha");

        jPasswordFieldSenhaUsuario.setEnabled(false);

        jPasswordFieldConfSenhaUsuario.setEnabled(false);
        jPasswordFieldConfSenhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfSenhaUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo");

        jComboBoxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Médico", "RH", "Recepcionista" }));
        jComboBoxTipoUsuario.setEnabled(false);
        jComboBoxTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoUsuarioActionPerformed(evt);
            }
        });

        jButtonCadUsNovo.setText("Novo");
        jButtonCadUsNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsNovoActionPerformed(evt);
            }
        });

        jButtonCadUsSalvar.setText("Salvar");
        jButtonCadUsSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsSalvarActionPerformed(evt);
            }
        });

        jButtonCadUsAlterar.setText("Alterar");
        jButtonCadUsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsAlterarActionPerformed(evt);
            }
        });

        jButtonCadUsExcluir.setText("Excluir");
        jButtonCadUsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsExcluirActionPerformed(evt);
            }
        });

        jButtonCadUsCancelar.setText("Cancelar");
        jButtonCadUsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsCancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("Pesquisa");

        jButtonCadUsBuscar.setText("Buscar");
        jButtonCadUsBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsBuscarActionPerformed(evt);
            }
        });

        jTableCadUsPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCadUsPesquisa);

        jLabel8.setText("Cod.");

        jTextFieldCadUsCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonCadUsSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadUsAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jButtonCadUsNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonCadUsCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadUsExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPasswordFieldSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldConfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCadUsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCadUsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCadUsBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCadUsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadUsNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadUsSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldConfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadUsAlterar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadUsExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadUsCancelar)
                        .addGap(632, 632, 632))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldCadUsPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadUsBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(520, 520, 520))
        );

        setSize(new java.awt.Dimension(775, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoUsuarioActionPerformed

    private void jTextFieldLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginUsuarioActionPerformed

    private void jPasswordFieldConfSenhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfSenhaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldConfSenhaUsuarioActionPerformed

    private void jTextFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeUsuarioActionPerformed

    private void jButtonCadUsNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsNovoActionPerformed
        flag = 1;
        jTextFieldLoginUsuario.setEnabled(true);
        jTextFieldNomeUsuario.setEnabled(true);
        jPasswordFieldSenhaUsuario.setEnabled(true);
        jPasswordFieldConfSenhaUsuario.setEnabled(true);
        jComboBoxTipoUsuario.setEnabled(true);
        jButtonCadUsSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonCadUsNovoActionPerformed

    private void jButtonCadUsSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsSalvarActionPerformed
        if (jTextFieldNomeUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome do usuário");
            jTextFieldNomeUsuario.requestFocus();
        } else if (jTextFieldLoginUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o login do usuário");
            jTextFieldLoginUsuario.requestFocus();
        } else if (jPasswordFieldSenhaUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a senha do usuário");
            jTextFieldLoginUsuario.requestFocus();
        } else if (jPasswordFieldConfSenhaUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirme a senha do usuário");
            jTextFieldLoginUsuario.requestFocus();
        } else if (flag == 1) {
            mod.setNomeUsuario(jTextFieldNomeUsuario.getText());
            mod.setLoginUsuario(jTextFieldLoginUsuario.getText());
            mod.setSenhaUsuario(jPasswordFieldSenhaUsuario.getText());
            mod.setTipoUsuario((String) jComboBoxTipoUsuario.getSelectedItem());
            dao.Salvar(mod);
            jTextFieldNomeUsuario.setText("");
            jTextFieldLoginUsuario.setText("");
            jPasswordFieldSenhaUsuario.setText("");
            jPasswordFieldConfSenhaUsuario.setText("");
            jTextFieldNomeUsuario.setEnabled(false);
            jTextFieldLoginUsuario.setEnabled(false);
            jPasswordFieldSenhaUsuario.setEnabled(false);
            jPasswordFieldConfSenhaUsuario.setEnabled(false);
            jComboBoxTipoUsuario.setEnabled(false);
            jButtonCadUsSalvar.setEnabled(false);
        } else {
            
            mod.setNomeUsuario(jTextFieldNomeUsuario.getText());
            mod.setLoginUsuario(jTextFieldLoginUsuario.getText());
            mod.setSenhaUsuario(jPasswordFieldSenhaUsuario.getText());
            mod.setTipoUsuario((String) jComboBoxTipoUsuario.getSelectedItem());
            dao.Alterar(mod);
            jTextFieldNomeUsuario.setText("");
            jTextFieldLoginUsuario.setText("");
            jPasswordFieldSenhaUsuario.setText("");
            jPasswordFieldConfSenhaUsuario.setText("");
            jTextFieldNomeUsuario.setEnabled(false);
            jTextFieldLoginUsuario.setEnabled(false);
            jPasswordFieldSenhaUsuario.setEnabled(false);
            jPasswordFieldConfSenhaUsuario.setEnabled(false);
            jComboBoxTipoUsuario.setEnabled(false);
            jButtonCadUsSalvar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonCadUsSalvarActionPerformed

    private void jButtonCadUsBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsBuscarActionPerformed
        mod.setPesquisaUsuario(jTextFieldCadUsPesquisar.getText());
        BeansUsuario model = dao.buscaUsuario(mod);
        jTextFieldCadUsCodigo.setText(String.valueOf(model.getCodUsuario()));
        jTextFieldNomeUsuario.setText(model.getNomeUsuario());
        jTextFieldLoginUsuario.setText(model.getLoginUsuario());
        jPasswordFieldSenhaUsuario.setText(model.getSenhaUsuario());
        jPasswordFieldConfSenhaUsuario.setText(model.getSenhaUsuario());
        jComboBoxTipoUsuario.setSelectedItem(model.getTipoUsuario());
        jButtonCadUsExcluir.setEnabled(true);
        jButtonCadUsAlterar.setEnabled(true);

    }//GEN-LAST:event_jButtonCadUsBuscarActionPerformed

    private void jButtonCadUsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsAlterarActionPerformed
        flag = 2;
        jTextFieldLoginUsuario.setEnabled(true);
        jTextFieldNomeUsuario.setEnabled(true);
        jPasswordFieldSenhaUsuario.setEnabled(true);
        jPasswordFieldConfSenhaUsuario.setEnabled(true);
        jComboBoxTipoUsuario.setEnabled(true);
        jButtonCadUsSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonCadUsAlterarActionPerformed

    private void jButtonCadUsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir os dados?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCodUsuario(Integer.parseInt(jTextFieldCadUsCodigo.getText()));
            dao.Excluir(mod);
        }
    }//GEN-LAST:event_jButtonCadUsExcluirActionPerformed

    private void jButtonCadUsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadUsCancelarActionPerformed

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Login", "Tipo"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("cod_usuario"), conex.rs.getString("nome_usuario"), conex.rs.getString("login_usuario"), conex.rs.getString("tipo_usuario")});
            } while (conex.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado");
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableCadUsPesquisa.setModel(modelo);
        jTableCadUsPesquisa.getColumnModel().getColumn(0).setPreferredWidth(43);
        jTableCadUsPesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTableCadUsPesquisa.getColumnModel().getColumn(1).setPreferredWidth(190);
        jTableCadUsPesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTableCadUsPesquisa.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTableCadUsPesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTableCadUsPesquisa.getColumnModel().getColumn(3).setPreferredWidth(110);
        jTableCadUsPesquisa.getColumnModel().getColumn(3).setResizable(false);
        jTableCadUsPesquisa.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTableCadUsPesquisa.getColumnModel().getColumn(4).setResizable(false);
        jTableCadUsPesquisa.getTableHeader().setReorderingAllowed(false);
        jTableCadUsPesquisa.setAutoResizeMode(jTableCadUsPesquisa.AUTO_RESIZE_OFF);
        jTableCadUsPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconectar();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadUsAlterar;
    private javax.swing.JButton jButtonCadUsBuscar;
    private javax.swing.JButton jButtonCadUsCancelar;
    private javax.swing.JButton jButtonCadUsExcluir;
    private javax.swing.JButton jButtonCadUsNovo;
    private javax.swing.JButton jButtonCadUsSalvar;
    private javax.swing.JComboBox jComboBoxTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfSenhaUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenhaUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadUsPesquisa;
    private javax.swing.JTextField jTextFieldCadUsCodigo;
    private javax.swing.JTextField jTextFieldCadUsPesquisar;
    private javax.swing.JTextField jTextFieldLoginUsuario;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
