/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import modeloConection.ConexaoBD;

public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();

    public TelaPrincipal() {
        initComponents();
        conecta.conexao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameApresentacao = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jLabelImagem1 = new javax.swing.JLabel();
        jLabelImagem2 = new javax.swing.JLabel();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabelMensagem = new javax.swing.JLabel();
        jButtonSairMensagem = new javax.swing.JButton();
        jLabelFundoSistema = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadFuncionarios = new javax.swing.JMenuItem();
        jMenuItemCadMedicos = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameApresentacao.setTitle("Apresentação");
        jInternalFrameApresentacao.setVisible(true);
        jInternalFrameApresentacao.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jLabelImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fabio2.png"))); // NOI18N
        jLabelImagem1.setToolTipText("Fabio Silva 09062846");
        jPanelInternal.add(jLabelImagem1);
        jLabelImagem1.setBounds(20, 10, 200, 210);

        jLabelImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vitor2.png"))); // NOI18N
        jLabelImagem2.setToolTipText("Vitor Grillo ");
        jPanelInternal.add(jLabelImagem2);
        jLabelImagem2.setBounds(240, 10, 200, 210);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela.png"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(4, 4, 450, 230);

        jInternalFrameApresentacao.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(10, 30, 460, 240);

        jLabelMensagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMensagem.setText("Trabalho de POO - Prof. André/Pain - Turma 2015 - Noturno");
        jInternalFrameApresentacao.getContentPane().add(jLabelMensagem);
        jLabelMensagem.setBounds(10, 0, 420, 30);

        jButtonSairMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair2.jpg"))); // NOI18N
        jButtonSairMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairMensagemActionPerformed(evt);
            }
        });
        jInternalFrameApresentacao.getContentPane().add(jButtonSairMensagem);
        jButtonSairMensagem.setBounds(440, 0, 30, 30);

        getContentPane().add(jInternalFrameApresentacao);
        jInternalFrameApresentacao.setBounds(10, 20, 490, 300);

        jLabelFundoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela.png"))); // NOI18N
        getContentPane().add(jLabelFundoSistema);
        jLabelFundoSistema.setBounds(-6, 4, 610, 340);

        jMenuCadastro.setText("Cadastros");

        jMenuItemCadFuncionarios.setText("Funcionários");
        jMenuCadastro.add(jMenuItemCadFuncionarios);

        jMenuItemCadMedicos.setText("Médicos");
        jMenuItemCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMedicos);

        jMenuItemCadUsuarios.setText("Usuários");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemSobre);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemSairMouseClicked(evt);
            }
        });
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(620, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairMensagemActionPerformed
        jInternalFrameApresentacao.dispose();
    }//GEN-LAST:event_jButtonSairMensagemActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        jInternalFrameApresentacao.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicosActionPerformed
        CadastroMedico tela = new CadastroMedico();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMedicosActionPerformed

    private void jMenuItemSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairMouseClicked

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        TelaUsuario tela = new TelaUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSairMensagem;
    private javax.swing.JInternalFrame jInternalFrameApresentacao;
    private javax.swing.JLabel jLabelFundoSistema;
    private javax.swing.JLabel jLabelImagem1;
    private javax.swing.JLabel jLabelImagem2;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadFuncionarios;
    private javax.swing.JMenuItem jMenuItemCadMedicos;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
